/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { motion } from "framer-motion-3d";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
    const { nodes, materials } = useGLTF("models/Room.glb");
    return (
        <group {...props} dispose={null}>
            <group
                position={[-1.852, 0.09, -0.021]}
                rotation={[-Math.PI / 2, 0, -1.576]}
                scale={2.009}
            >
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group scale={0.01}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.ChairBack_LP_lambert1_0.geometry}
                            material={materials.lambert1}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.ChairSeat_LP4_lambert1_0.geometry}
                            material={materials.lambert1}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Leg_LP1_lambert1_0.geometry}
                            material={materials.lambert1}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Leg_LP2_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[5.602, 0, 4.07]}
                            rotation={[0, -1.257, 0]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Leg_LP3_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[3.463, 0, 10.655]}
                            rotation={[Math.PI, -Math.PI / 5, Math.PI]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Leg_LP4_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-3.462, 0, 10.655]}
                            rotation={[-Math.PI, Math.PI / 5, -Math.PI]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Leg_LP5_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-5.602, 0, 4.07]}
                            rotation={[0, 1.257, 0]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCube37_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-33.983, 64.178, -14.779]}
                            scale={[0.061, 0.036, 0.062]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCube38_lambert1_0.geometry}
                            material={materials.lambert1}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder25_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-58.139, 0, 48.659]}
                            rotation={[-Math.PI, 0.114, -Math.PI]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder26_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[31.27, 0, -31.948]}
                            rotation={[0, 0.895, 0]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder27_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-3.632, 0, 3.211]}
                            rotation={[0, 1.2, 0]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder28_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-26.088, 0, -16.813]}
                            rotation={[-Math.PI, 0.492, -Math.PI]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder29_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-64.369, 0, -4.511]}
                            rotation={[-Math.PI, 0.495, -Math.PI]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Underside_LP_lambert1_0.geometry}
                            material={materials.lambert1}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Wheel_LP_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-58.139, 0, 48.659]}
                            rotation={[-Math.PI, 0.114, -Math.PI]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Wheel_LP1_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[31.27, 0, -31.948]}
                            rotation={[0, 0.895, 0]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Wheel_LP2_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-3.632, 0, 3.211]}
                            rotation={[0, 1.2, 0]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Wheel_LP3_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-26.088, 0, -16.813]}
                            rotation={[-Math.PI, 0.492, -Math.PI]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Wheel_LP4_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-64.369, 0, -4.511]}
                            rotation={[-Math.PI, 0.495, -Math.PI]}
                        />
                    </group>
                </group>
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane.geometry}
                material={materials.Walls}
                scale={4}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001.geometry}
                material={materials.White}
                position={[-3.543, 1.863, -0.028]}
                scale={[0.391, 0.07, 4]}
            />
            <group position={[-0.154, -0.563, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002_1.geometry}
                    material={materials.Black}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002_2.geometry}
                    material={materials["Material.003"]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube003.geometry}
                material={materials.Black}
                position={[-3.732, 2.202, -0.07]}
                rotation={[0, 0, -Math.PI]}
                scale={[-0.051, -0.199, -0.099]}
            />
            <group position={[-3.541, 3.01, 1.931]} rotation={[0, 0.21, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube004_1.geometry}
                    material={materials.Black}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube004_2.geometry}
                    material={materials["Material.001"]}
                />
            </group>
            <group position={[-0.07, -0.563, -1.359]} rotation={[0, -0.184, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005_1.geometry}
                    material={materials.Black}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005_2.geometry}
                    material={materials["Material.002"]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube006.geometry}
                material={nodes.Cube006.material}
                position={[2.409, 0.226, 2.099]}
                rotation={[0, 0, -Math.PI]}
                scale={[-1, -0.226, -1.784]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube007.geometry}
                material={nodes.Cube007.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube008.geometry}
                material={nodes.Cube008.material}
                position={[4.859, 1.197, 0]}
                rotation={[0, 0, Math.PI]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane001.geometry}
                material={materials.Material}
                position={[2.41, 1.319, 1.868]}
                scale={[1.139, 1.051, 1.581]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube009.geometry}
                material={nodes.Cube009.material}
                position={[2.807, 0.843, 3.218]}
            />
            <group
                position={[0.234, 2.689, -4]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1.707, 1, 1]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane002_1.geometry}
                    material={materials.Black}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane002_2.geometry}
                    material={materials.f1Screen}
                />
            </group>
            <group
                position={[-3.463, 1.944, -0.059]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            >
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[-0.018, 0.074, 0.11]}
                        rotation={[0.024, 0, 0]}
                        scale={[0.318, 0.075, 0.137]}
                    >
                        <group
                            position={[-0.143, -0.567, 0.718]}
                            scale={[0.104, 0.439, 0.241]}
                        >
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_10.geometry}
                                material={materials.White_Keys_7}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_11.geometry}
                                material={materials.Black_Keys_1}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_12.geometry}
                                material={materials["Arrow.001"]}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_13.geometry}
                                material={materials.White_Keys_3}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_14.geometry}
                                material={materials.Black_Keys_5}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_15.geometry}
                                material={materials.Black_keys_4}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_16.geometry}
                                material={materials.Black_Keys_3}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_17.geometry}
                                material={materials.material}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_18.geometry}
                                material={materials.White_Keys_4}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_19.geometry}
                                material={materials.Black_Keys_2}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_20.geometry}
                                material={materials.White_Keys_5}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_21.geometry}
                                material={materials["Material.005"]}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_22.geometry}
                                material={materials["Material.006"]}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_5.geometry}
                                material={materials.Space}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_6.geometry}
                                material={materials.White_Keys_2}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_7.geometry}
                                material={materials["Material.004"]}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_8.geometry}
                                material={materials.Shift_Arrow}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_9.geometry}
                                material={materials.White_Keys_1}
                            />
                        </group>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_24.geometry}
                            material={materials.Polycarbonate_Case}
                            position={[0.778, -1.016, -0.785]}
                            rotation={[-0.028, 0, 0]}
                            scale={[3.149, 13.351, 7.317]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_26.geometry}
                            material={materials.Alumunium_Knob}
                            position={[0.854, -0.383, -0.669]}
                            rotation={[0.059, 0, 0]}
                            scale={[3.116, 13.472, 7.256]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_28.geometry}
                            material={materials.Polycarbonate_Case}
                            position={[-0.571, -0.58, 0.014]}
                            rotation={[0.039, 0, 0]}
                            scale={[3.149, 13.349, 7.322]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_30.geometry}
                            material={materials.Polycarbonate_Case}
                            position={[0.008, -0.95, -0.01]}
                            rotation={[-0.005, 0, 0]}
                            scale={[3.149, 13.354, 7.312]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_32.geometry}
                            material={materials.Polycarbonate_Case}
                            position={[-0.724, -1.008, 0.795]}
                            rotation={[-0.005, 0, 0]}
                            scale={[3.149, 13.354, 7.312]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_34.geometry}
                            material={materials.Polycarbonate_Case}
                            position={[-0.881, -1.05, -0.624]}
                            rotation={[0.015, 0, 0]}
                            scale={[3.149, 13.353, 7.314]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_36.geometry}
                            material={materials.Plate_Metal}
                            position={[0.01, -0.595, 0.039]}
                            rotation={[-0.021, 0, 0]}
                            scale={[3.149, 13.352, 7.315]}
                        />
                    </group>
                </group>
            </group>
            {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.Black}
        position={[0, -0.578, 0]}
        scale={-21.957}
      /> */}
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_1.geometry}
                material={materials.White}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_2.geometry}
                material={materials.DarkGrey}
            />
        </group>
    );
}

useGLTF.preload("models/Room.glb");
