/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function HologramPedestal(props) {
    const { nodes, materials } = useGLTF("models/HologramPedestal.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pedestal.geometry}
                material={materials.Pedestal}
                scale={[1, 0.105, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder.geometry}
                material={materials.Hologram}
                position={[0, 1.647, 0]}
                scale={1.31}
            />
        </group>
    );
}

useGLTF.preload("models/HologramPedestal.glb");
